#include <stdio.h>
#include <math.h>

#define RUN_COUNT 200
#define SIMD_LEN 4
#define SIMD_RUN_COUNT RUN_COUNT/SIMD_LEN
#define PERCENT 0.1
#define LIBMV_COUNT 10
#define SIMD_MC_LEN 4
#define SIMD_CG_LEN 8
#define SIMD_MC_COUNT 50
#define SIMD_CG_COUNT 25
#define FRA_TRAVERSED_COUNT 12
#define FRA_TRAVERSED_POW pow(2,FRA_TRAVERSED_COUNT)
#define FRA_TRAVERSED_COUNT_DOUBLE 26
#define FRA_TRAVERSED_POW_DOUBLE pow(2,FRA_TRAVERSED_COUNT)
#define FLOAT_DATA_LENGTH 256*FRA_TRAVERSED_POW
