fprintf(func, "/** target func:	exp\n");
fprintf(func, "*** target domain:	[-3.000000, 3.000000]\n");
fprintf(func, "*** target precision:	90\n");
fprintf(func, "**/\n");
fprintf(func, "#include <stdio.h>\n");
fprintf(func, "#include <math.h>\n");
fprintf(func, "#include "myhead.h"\n");
fprintf(func, "\n");
fprintf(func, "#define BIT 6\n");
fprintf(func, "#define BITNUM 64\n");
fprintf(func, "#define DEGREE 6\n");
fprintf(func, "\n");
fprintf(func, "static const DL\n");
fprintf(func, "coefficient[DEGREE] = {\n");
fprintf(func, "	{.d = 1},\n");
fprintf(func, "	{.d = 1},\n");
fprintf(func, "	{.d = 0.5},\n");
fprintf(func, "	{.d = 1.0 / 6.0},\n");
fprintf(func, "	{.d = 1.0 / 24.0},\n");
fprintf(func, "	{.d = 1.0 / 120.0},\n");
fprintf(func, "};\n");
fprintf(func, "\n");
fprintf(func, "double exp_gen(double x) {\n");
fprintf(func, "	double temp;\n");
fprintf(func, "	int k;\n");
fprintf(func, "	double k1;\n");
fprintf(func, "	double T;\n");
fprintf(func, "	long int T_int;\n");
fprintf(func, "	double r;\n");
fprintf(func, "	double r_poly;\n");
fprintf(func, "	int hi, lo;\n");
fprintf(func, "	double r_coefficient;\n");
fprintf(func, "	double result;\n");
fprintf(func, "\n");
fprintf(func, "	k = BITNUM;\n");
fprintf(func, "	k1 = k / log(2);\n");
fprintf(func, "	T = x * k1;\n");
fprintf(func, "	T_int = T;\n");
fprintf(func, "	// 0 <= r <= 1/k1\n");
fprintf(func, "	r = x - ((double)T_int)/k1;\n");
fprintf(func, "	r_poly = coefficient[0].d + r * (coefficient[1].d + r * (coefficient[2].d + r * (coefficient[3].d + r * (coefficient[4].d + r * (coefficient[5].d + 0)))));\n");
fprintf(func, "	lo = T_int % k;\n");
fprintf(func, "	hi = T_int / k;\n");
fprintf(func, "	r_coefficient = pow(2, (double)hi) * pow(2, ((double)lo / k));\n");
fprintf(func, "	result = r_coefficient * r_poly;\n");
fprintf(func, "\n");
fprintf(func, "	return result;\n");
fprintf(func, "}\n");
fprintf(func, "\n");
