fprintf(func, "#include <stdio.h>\n");
fprintf(func, "#include <math.h>\n");
fprintf(func, "#include "myhead.h"\n");
fprintf(func, "\n");
fprintf(func, "#define BIT 6\n");
fprintf(func, "#define BITNUM 64\n");
fprintf(func, "#define DEGREE 6\n");
fprintf(func, "\n");
fprintf(func, "static const double\n");
fprintf(func, "ln2HI = 6.93147180369123816490e-01,  /* 0x3fe62e42, 0xfee00000 */\n");
fprintf(func, "ln2LO = 1.90821492927058770002e-10, /* 0x3dea39ef, 0x35793c76 */\n");
fprintf(func, "invln2 = 1.44269504088896338700e+00; /* 0x3ff71547, 0x652b82fe */\n");
fprintf(func, "\n");
fprintf(func, "static const double\n");
fprintf(func, "interpolate[BITNUM] = {\n");
fprintf(func, "	0\n");
fprintf(func, "};\n");
fprintf(func, "static const DL\n");
fprintf(func, "coefficient[DEGREE] = {\n");
fprintf(func, "	{.d = 1},\n");
fprintf(func, "	{.d = 1},\n");
fprintf(func, "	{.d = 0.5},\n");
fprintf(func, "	{.d = 1.0 / 6.0},\n");
fprintf(func, "	{.d = 1.0 / 24.0},\n");
fprintf(func, "	{.d = 1.0 / 120.0}\n");
fprintf(func, "};\n");
fprintf(func, "\n");
fprintf(func, "double exp_gen(double x) {\n");
fprintf(func, "	double temp;\n");
fprintf(func, "	int k;\n");
fprintf(func, "	double k1;\n");
fprintf(func, "	double T;\n");
fprintf(func, "	long int T_int;\n");
fprintf(func, "	double r;\n");
fprintf(func, "	double r_poly;\n");
fprintf(func, "	unsigned long int hi, lo;\n");
fprintf(func, "	double r_coefficient;\n");
fprintf(func, "	double result;\n");
fprintf(func, "	double r_hi, r_lo;\n");
fprintf(func, "\n");
fprintf(func, "	k = BITNUM;\n");
fprintf(func, "	k1 = k * invln2;\n");
fprintf(func, "	T = x * k1;\n");
fprintf(func, "	T_int = T;\n");
fprintf(func, "	// 0 <= r <= 1/k1\n");
fprintf(func, "	r = x - T_int * ln2HI;\n");
fprintf(func, "	r = r - T_int * ln2LO;\n");
fprintf(func, "	r_poly = coefficient[0].d + r * (coefficient[1].d + r * (coefficient[2].d + r * (coefficient[3].d + r * (coefficient[4].d + r * (coefficient[5].d + 0)))));\n");
fprintf(func, "	lo = T_int % k;\n");
fprintf(func, "	hi = T_int / k;\n");
fprintf(func, "	hi = hi << 52;\n");
fprintf(func, "	r_hi = *((double *)&hi);\n");
fprintf(func, "	r_lo = pow(2, (lo / k));\n");
fprintf(func, "	r_coefficient = r_hi * r_lo;\n");
fprintf(func, "	result = r_coefficient * r_poly;\n");
fprintf(func, "\n");
fprintf(func, "	return result;\n");
fprintf(func, "}\n");
fprintf(func, "\n");
